spring.application.name=event-ticketing
spring.datasource.url=jdbc:postgresql://localhost:5432/event_ticketing
spring.datasource.username=postgres
spring.datasource.password=xaris123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true